// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpCqMgueKg0YXIJAJ5izVLVXzpzpIizI',
    appId: '1:238574230265:web:a329f8d1699d775989e028',
    messagingSenderId: '238574230265',
    projectId: 'e-commerce-app-3b4b9',
    authDomain: 'e-commerce-app-3b4b9.firebaseapp.com',
    storageBucket: 'e-commerce-app-3b4b9.firebasestorage.app',
    measurementId: 'G-J4Q257JMDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9vo19tJqZTzRKHFmIqgPRZhcZpZMP9CE',
    appId: '1:238574230265:android:ceb1418eb35331dd89e028',
    messagingSenderId: '238574230265',
    projectId: 'e-commerce-app-3b4b9',
    storageBucket: 'e-commerce-app-3b4b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNh-dYKh2nczmsRX1E3aBRT35gul2-bq4',
    appId: '1:238574230265:ios:678c6bc61b2673d889e028',
    messagingSenderId: '238574230265',
    projectId: 'e-commerce-app-3b4b9',
    storageBucket: 'e-commerce-app-3b4b9.firebasestorage.app',
    iosBundleId: 'com.example.locally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNh-dYKh2nczmsRX1E3aBRT35gul2-bq4',
    appId: '1:238574230265:ios:678c6bc61b2673d889e028',
    messagingSenderId: '238574230265',
    projectId: 'e-commerce-app-3b4b9',
    storageBucket: 'e-commerce-app-3b4b9.firebasestorage.app',
    iosBundleId: 'com.example.locally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFpCqMgueKg0YXIJAJ5izVLVXzpzpIizI',
    appId: '1:238574230265:web:d728d7b9fade65ff89e028',
    messagingSenderId: '238574230265',
    projectId: 'e-commerce-app-3b4b9',
    authDomain: 'e-commerce-app-3b4b9.firebaseapp.com',
    storageBucket: 'e-commerce-app-3b4b9.firebasestorage.app',
    measurementId: 'G-NJ31C4P0MM',
  );
}
